#include "LeoFS.h"

void print_error_trace();
void reverse_endianess(void *ptr, unsigned int length);
void reverse_descriptor_endianess(struct LFSObjectDescriptor *str);
void get_fs_info();
void print_menu();
int get_choice();
void switch_choice(int n);
void print_date(struct full_date_t date);
void print_object_data(struct LFSObjectDescriptor obj);
int u_get_object(struct LFSObjectDescriptor *obj);
int u_get_choice();
void f_delete_object();
void f_create_directory();
void f_read_block();
void f_get_block_info();
void f_get_object_info();
void f_get_fs_info();
void f_migrate_object();
void f_read_object();
void f_edit_object_info();
void f_move_to_leofs();
void f_move_to_host();
void check_fs_integrity();
void load_root_descriptor();
void init_fs();
void init_descriptor(struct LFSObjectDescriptor *str, char *name, uint32_t first_block, unsigned char permissions, enum LFSObjectType type);
int write_block(struct LFSBlock *block, const unsigned long block_n);
int read_block(struct LFSBlock *block, const unsigned long block_n);
int is_block_free(const unsigned long n);
long find_free_block();
int reserve_block(const unsigned int block_n);
void free_block(const unsigned int block_n);
int get_last_block(struct LFSObjectDescriptor *descr);
int get_free_space(struct LFSObjectDescriptor *descr);
void init_block(struct LFSBlock *block, unsigned int prev, unsigned int next);
void write_block_data(unsigned int block, void *data, unsigned int size);
int update_descriptor(struct LFSObjectDescriptor *descr);
int add_block(struct LFSObjectDescriptor *str);
int get_next_block(int block);
int get_previous_block(int block);
int read_object(void *buf, struct LFSObjectDescriptor *start);
int write_object(void *data, const unsigned long size, const unsigned long start_block, struct LFSObjectDescriptor *descr);
int add_data_to_object(struct LFSObjectDescriptor *str, void *data, unsigned long size);
int delete_object_data(struct LFSObjectDescriptor *object);
void update_size(struct LFSObjectDescriptor *str);
void update_bsize(struct LFSObjectDescriptor *str);
int read_raw_block(unsigned long block_n, void *buf);
int descriptor_from_location(unsigned int block, unsigned short offset, struct LFSObjectDescriptor *descr);
int create_object(struct LFSObjectDescriptor *parent, struct LFSObjectDescriptor *obj, char *name);
int mkdir_from_descriptor(struct LFSObjectDescriptor *parent, struct LFSObjectDescriptor *subdir, char *name);
int read_dir_from_descriptor(struct LFSObjectDescriptor *dir, struct LFSObjectDescriptor array[]) ;
int remove_descriptor(struct LFSObjectDescriptor *target);
int delete_object(struct LFSObjectDescriptor *target);
int migrate_from_descriptor(struct LFSObjectDescriptor *src, struct LFSObjectDescriptor *dest);
int mkfile(struct LFSObjectDescriptor *parent, struct LFSObjectDescriptor *file, char *name, void *data, unsigned long size);
int mkdir_from_path(char *path, char *name, struct LFSObjectDescriptor *child);
int rmdir_from_path(char *path);
int scan_directory(char *path, struct LFSObjectDescriptor *des);
int directory_exist_descr(struct LFSObjectDescriptor dir);
int are_equal(struct LFSObjectDescriptor obj1, struct LFSObjectDescriptor obj2);
void print_directory(struct LFSObjectDescriptor dir);
void validate_object_name(char *str);
char is_valid(struct LFSObjectDescriptor obj);
char is_edited(struct LFSObjectDescriptor obj);
char is_hidden(struct LFSObjectDescriptor obj);
char is_locked(struct LFSObjectDescriptor obj);
char is_root(struct LFSObjectDescriptor obj);
char is_corrupted(struct LFSObjectDescriptor obj);
char is_orphan(struct LFSObjectDescriptor obj);
